import { PageLayout } from "@/layout/PageLayout";
import { dataSet } from "@/components/FoodItem";
import Head from "next/head";
import styles from "@/styles/Home.module.css";
import { useRouter } from "next/router";
import React from "react";
import Image from "next/image";
import Link from "next/link";

const Order = () => {
  const { order } = useRouter().query;
  const data = dataSet[order - 1];
  console.log(data);
  return (
    <>
      <Head>
        <title>StarX | Order</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <PageLayout url="userhome" text="My Order">
        <div
          className={`${styles.card} p-4 mx-4 mt-[3rem] flex flex-col gap-4 justify-around`}
        >
          <div className="flex justify-between items-start h-[4rem]">
            <div className="flex gap-4">
              <Image
                src={`/${data?.src}`}
                alt="food-item"
                width={50}
                height={50}
              />
              <p>{data?.text}</p>
            </div>
            <Image
              src="/ri-more-2-fill.svg"
              alt="icon"
              width={20}
              height={20}
            />
          </div>
          <div className="flex justify-center items-center gap-2">
            <Image src="/Vector (1).svg" alt="icon" width={20} height={20} />
            <span>30mins to prepare</span>
          </div>
        </div>
        <Link
          href={`/ticket/${data?.id}`}
          className="w-full text-center flex justify-center mt-[6rem]"
        >
          <button className="border-2 border-gray-500 rounded-lg py-4 px-[3rem] shadow-xl text-lg">
            Get Meal Ticket
          </button>
        </Link>
      </PageLayout>
    </>
  );
};

export default Order;
