import { List } from "@/components/List";
import { PageLayout } from "@/layout/PageLayout";
import Head from "next/head";
import React from "react";

const history = () => {
  return (
    <>
      <Head>
        <title>StarX | History</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <PageLayout url="userhome" text="Meal History">
        <List />
      </PageLayout>
    </>
  );
};

export default history;
