import Head from "next/head";
import React from "react";

const history = () => {
  return (
    <>
      <Head>
        <title>StarX | Home</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>Order History Page</div>
    </>
  );
};

export default history;
