import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import Link from "next/link";

// const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>StarX | Home</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={`${styles.center} pt-[2rem]`}>
          <Image
            src="/StarXstarXlogo.svg"
            alt="StarX Logo"
            width={180}
            height={37}
            priority
          />
        </div>

        <div className={`${styles.center} px-0`}>
          <Image
            src="/undraw_eating_together_re_ux62 (1).png"
            alt="StarX Hero Image"
            width={400}
            height={300}
            priority
          />
        </div>
        <Link href="/login" className="w-full lg:w-[30rem]">
          <button className="bg-green-600 p-3 text-white rounded-lg w-full">
            Login
          </button>
        </Link>
        <Link href="/register" className="w-full lg:w-[30rem]">
          <button className="border-2 border-green-600 rounded-lg p-3 w-full">
            Register
          </button>
        </Link>
      </main>
    </>
  );
}
