import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import React from "react";
import styles from "@/styles/Home.module.css";

const login = () => {
  return (
    <>
      <Head>
        <title>StarX | Login</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={`${styles.center} pt-[2rem] mb-10`}>
          <Image
            src="/StarXstarXlogo.svg"
            alt="StarX Logo"
            width={180}
            height={37}
            priority
          />
        </div>

        <div className={`${styles.center} px-0 my-10`}>
          <Image
            src="/undraw_breakfast_psiw (1) 1.svg"
            alt="StarX Hero Image"
            width={400}
            height={300}
            priority
          />
        </div>

        <input
          type="text"
          className="border-2 border-[#428837] rounded-lg p-3 w-full lg:w-[30rem] mb-2"
          placeholder="Id Number"
        />
        <input
          type="password"
          className="border-2 border-[#428837] rounded-lg p-3 w-full lg:w-[30rem] mb-[-0.5rem]"
          placeholder="Password"
        />
        <Link href="#" className="m-0 text-right w-full lg:w-[30rem] text-sm">
          Forgot Password?
        </Link>
        <Link href="/userhome" className="w-full lg:w-[30rem]">
          <button className="bg-gray-300 border-2 border-gray-400 rounded-lg p-3 w-full lg:w-[30rem]">
            Login
          </button>
        </Link>
      </main>
    </>
  );
};

export default login;
