import { List } from "@/components/List";
import { PageLayout } from "@/layout/PageLayout";
import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import React from "react";

const more = () => {
  return (
    <>
      <Head>
        <title>StarX | More</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <PageLayout url="profile" text="More">
        <div className="mt-[2rem] border-t-2 border-b-2 border-gray-400">
          <Link href="#" className="flex gap-4 mx-6 my-10 pb-4 border-b-2">
            <Image src="/Vector (2).svg" alt="icon" width={20} height={20} />
            <h2>Settings</h2>
          </Link>
          <Link href="#" className="flex gap-4 mx-6 my-10 pb-4 border-b-2">
            <Image src="/Vector (3).svg" alt="icon" width={20} height={20} />
            <h2>About</h2>
          </Link>
          <Link href="#" className="flex gap-4 mx-6 my-10">
            <Image src="/Vector (4).svg" alt="icon" width={20} height={20} />
            <h2>Appearance</h2>
          </Link>
        </div>
      </PageLayout>
    </>
  );
};

export default more;
