import Head from "next/head";
//import {React, useState } from "react";
import Image from "next/image";
import Link from "next/link";
import React from "react";
import { Navbar } from "@/components/Navbar";
import styles from "@/styles/Home.module.css";
import { PageLayout } from "@/layout/PageLayout";

const profile = () => {
  //const [image, setImage] = useState(null);
  //const {user, loading} = useFetchUser();
  return (
    <>
      <Head>
        <title>StarX | Profile</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="lg:w-[30rem] mx-auto">
        <div>
          <div className="flex flex-col gap-6 mt-4 items-start">
            <Link href="/userhome">
              <div className="flex items-center mt-[2rem] px-2">
                <span>
                  <Image
                    src="/Vector.svg"
                    alt="back-arrow"
                    width={24}
                    height={24}
                  />
                </span>
                <span>Back</span>
              </div>
            </Link>
            <div className="flex justify-end w-full mt-[-1.5rem] pr-2">
              <Image src="/alarm.svg" alt="alarm" width={20} height={20} />
            </div>
            <h1 className="text-xl w-full text-left px-4 mb-2 mt-[-1.5rem]">
              Profile
            </h1>
            <div className="flex gap-6">
              <div>
                <Image
                  src="/duns.jpg"
                  alt="profile01"
                  width={101.42}
                  height={101.42}
                  className="rounded-full ml-5 left-[20px] top-[164px] border-2 border-[#428837]"
                />
              </div>
              <div className="">
                <div className="mt-4 font-semibold text-lg">
                  <h4>Faith M. Roberts</h4>
                </div>
                <div>
                  <h6>7864FJI</h6>
                </div>
              </div>
            </div>
          </div>
          <Link href="#">
            <button className="bg-[#428837] mt-6 ml-28 rounded-lg h-12 px-8 w-140 shadow-xl text-white">
              Edit Profile
            </button>
          </Link>
        </div>
        <Navbar />
      </main>
    </>
  );
};
export default profile;
