import Head from "next/head";
//import {React, useState } from "react";
import Image from "next/image";
import Link from "next/link";
import React from "react";
import { Navbar } from "@/components/Navbar";
import styles from "@/styles/Home.module.css";
import { PageLayout } from "@/layout/PageLayout";

const profile = () => {
  //const [image, setImage] = useState(null);
  //const {user, loading} = useFetchUser();
  return (
    <>
      <Head>
        <title>StarX | Profile</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <PageLayout url="history" text="Profile">
          <div className="">
            <div className="flex justify-end mr-6">
              <Image src="/alarm.svg" alt="alarm" width={20} height={20} />
            </div>

            <div className="flex gap-6 mt-4 items-start">
              <div className="">
                <Image
                  src="/duns.jpg"
                  alt="profile01"
                  width={101.42}
                  height={101.42}
                  className="rounded-full ml-5 left-[20px] top-[164px] border-2 border-[#428837]"
                />
              </div>
              <div className="">
                <div className="mt-4 font-semibold text-lg">
                  <h4>Faith M. Roberts</h4>
                </div>
                <div>
                  <h6>7864FJI</h6>
                </div>
              </div>
            </div>
            <Link href="/changePicture">
              <button className="bg-[#428837] mt-6 ml-28 rounded-lg h-12 px-8 w-140 shadow-xl text-white">
                Edit Profile
              </button>
            </Link>
          </div>
        </PageLayout>
      </main>
    </>
  );
};
export default profile;
