import Head from "next/head";
import React from "react";

const register = () => {
  return (
    <>
      <Head>
        <title>StarX | Register</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>Register Page</div>
    </>
  );
};

export default register;
