import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import React from "react";
import styles from "@/styles/Home.module.css";

const register = () => {
  return (
    <>
      <Head>
        <title>StarX | Register</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={`${styles.center} pt-[2rem]`}>
          <Image
            src="/StarXstarXlogo.svg"
            alt="StarX Logo"
            width={180}
            height={37}
            priority
          />
        </div>

        <input
          type="text"
          className="border-2 border-green-600 rounded-lg p-3 w-full lg:w-[30rem]"
          placeholder="First Name"
        />

        <input
          type="text"
          className="border-2 border-green-600 rounded-lg p-3 w-full lg:w-[30rem]"
          placeholder="Last Name"
        />

        <input
          type="email"
          className="border-2 border-green-600 rounded-lg p-3 w-full lg:w-[30rem]"
          placeholder="E-Mail Address"
        />

        <input
          type="number"
          className="border-2 border-green-600 rounded-lg p-3 w-full lg:w-[30rem]"
          placeholder="Phone Number"
        />
        <Link href="/employeeConfirmation" className="w-full">
          <button className="bg-gray-300 border-2 border-gray-400 rounded-lg p-3 w-full lg:w-[30rem]">
            Next
          </button>
        </Link>
      </main>
    </>
  );
};

export default register;
