import Head from "next/head";
import Link from "next/link";
import React from "react";
import styles from "@/styles/Home.module.css";
import { Navbar } from "@/components/Navbar";
import { FoodItem } from "@/components/FoodItem";

const kitchen = () => {
  return (
    <>
      <Head>
        <title>StarX | Confirm</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main
        className={`${styles.main} px-2 max-h-screen lg:w-[30rem] mt-[1rem]`}
      >
        <h2 className="text-left mt-[3rem] w-full text-xl mb-[2rem]">
          Welcome, Sandra
        </h2>
        <input
          className={`ring-1 ring-black rounded-lg py-2 px-9 w-full mb-6 ${styles.search}`}
          type="search"
          placeholder="What would you like to eat today?"
        />
        <FoodItem />

        <Navbar />
      </main>
    </>
  );
};

export default kitchen;
