import { dataSet } from "@/components/FoodItem";
import { PageLayout } from "@/layout/PageLayout";
import Head from "next/head";
import Image from "next/image";
import { useRouter } from "next/router";
import React from "react";

const ticket = () => {
  const { ticket } = useRouter().query;
  const data = dataSet[ticket - 1];
  console.log(data?.id);
  return (
    <>
      <Head>
        <title>StarX | Ticket</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <PageLayout url="userhome" text="Order Successful">
        <div>
          <p>Here's your Meal Ticket</p>
          <Image
            src={`/${data?.src}`}
            alt="ordered meal"
            width={50}
            height={50}
          />
          <p>{data?.text}</p>
        </div>
      </PageLayout>
    </>
  );
};
export default ticket;
